"""create todos table

Revision ID: 9a7e81479024
Revises: 5af9e5be0f81
Create Date: 2024-05-12 18:53:19.045028

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a7e81479024'
down_revision: Union[str, None] = '5af9e5be0f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'todos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'draft', 'todo', 'doing', 'done', 'trash', name='todostate'
            ),
            nullable=False,
        ),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('_prisma_migrations')
    op.alter_column(
        'users',
        'password',
        existing_type=sa.VARCHAR(length=250, collation='Latin1_General_BIN2'),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'avatar',
        existing_type=sa.VARCHAR(length=250, collation='Latin1_General_BIN2'),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'avatar',
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=250, collation='Latin1_General_BIN2'),
        existing_nullable=True,
    )
    op.alter_column(
        'users',
        'password',
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=250, collation='Latin1_General_BIN2'),
        existing_nullable=False,
    )
    op.create_table(
        '_prisma_migrations',
        sa.Column(
            'id',
            sa.VARCHAR(length=36, collation='Latin1_General_BIN2'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'checksum',
            sa.VARCHAR(length=64, collation='Latin1_General_BIN2'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'finished_at',
            mssql.DATETIMEOFFSET(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'migration_name',
            sa.NVARCHAR(length=250, collation='Latin1_General_BIN2'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'logs',
            sa.NVARCHAR(collation='Latin1_General_BIN2'),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'rolled_back_at',
            mssql.DATETIMEOFFSET(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'started_at',
            mssql.DATETIMEOFFSET(),
            server_default=sa.text('(getdate())'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'applied_steps_count',
            sa.INTEGER(),
            server_default=sa.text('((0))'),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name='PK___prisma___3213E83F9CE091D2'),
    )
    op.drop_table('todos')
    # ### end Alembic commands ###
